# Generated by Django 3.1.7 on 2021-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20210317_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='Data',
            field=models.DateTimeField(),
        ),
    ]
